w3itch-crafter/w3itch-backend

README.md
config/config.example.yaml
src/api/accounts/accounts-github/accounts-github.service.ts
src/api/accounts/accounts-token/accounts-token.controller.ts
src/api/accounts/accounts.service.ts
src/api/accounts/jwt-cookie-helper.service.ts
src/api/blockchains/tokens/web3.provider.ts
src/api/games/dto/create-game-proejct.dto.ts
src/api/games/games.logic.service.ts
src/api/tags/dto/update-tag.dto.ts
src/api/users/dto/validate-username.dto.ts
src/api/users/users.controller.ts
src/api/users/users.service.ts
src/auth/module.ts
src/auth/service.ts
src/auth/strategy.ts
src/configs/cache.ts
src/configs/winston.ts
src/entities/Game.entity.ts
src/entities/Tag.entity.ts
src/entities/User.entity.ts
src/main.ts

`POST /users/username/validate`
This API has been removed. Signup API will return 400 if the username isn't valid.
And I've added namespace to the config file. See below (copied from the example).
```bash
app:
name: w3itch-backend
port: 3002
bodyParser:
limit: 50mb
swagger:
enable: true
logger:
loki: …
```

feat: add custom message for regex validation; username validation

---

.gitignore
src/api/games/easy-rpg.games.service.ts
src/api/games/games.logic.service.ts
src/entities/Game.entity.ts

```
```
Fixed #12, and this [#53 issue](https://github.com/w3itch-crafter/w3itch-frontend/issues/53) was posted to the front-end issues.
**Desktop:**
- OS:

fix: gencache and file mimetype check

---

.gitignore
src/api/accounts/accounts-github/accounts-github.service.ts
src/api/games/easy-rpg.games.service.ts
src/api/games/games.logic.service.ts
src/main.ts

```
```
Fixed #9 
Because of the resource files can't be located during `gencache`, then Easy-RPG player can't find RTP files which doesn't have an extension. So we copy the RTP files right into the temporary game path and run `gencache`.
Fixed 500 error if the user clicked Cancel when authenticating. …

feat: gencache with RTP resources; update file when updating charset

---

config/config.example.yaml
package.json
src/api/storages/controller.ts
src/api/storages/dto.ts
src/api/storages/service.ts
yarn.lock

```
aws:
accessKeyId:
secretAccessKey:
bucket:
folder: w3itch-test/attachment
```
Upload a file to AWS bucket via this API, it returns `UploadtToAWSResultDto` like this for example:
```json
{
"publicUrl": "https://s3.amazonaws.com/image.w3itch.io/w3itch-test/attachment/1/ruina0.jpeg",
"eTag": …
```

feat: aws s3 storage service

---

config/config.example.yaml
src/api/blockchains/tokens/web3.provider.ts

```
blockchain:
infura:
apiToken:
supportedChainIds:
test: [1, 3, 4, 5, 42]
prod: [1, 10, 56, 137, 42161]
```
Support more blockchain networks, check the above for the list.
Also fixed #5.
I've tested `1, 10, 137, 42161` by myself, and they all work properly.
- …

feat: support more blockchains

---

config/config.example.yaml
src/api/blockchains/tokens/web3.provider.ts

The environment variables configuration has been changed from this:
```yaml
blockchain:
infura:
apiToken:
supportedChainIds:
test: [1, 3, 4, 5, 42]
prod: [1, 10, 56, 137, 42161]
```
To this:
```yaml
blockchain:
infura:
apiToken:
supportedChainIds: [1, 3, 4, 5, 10, 42, 56, 137, 42161]
```
``` …
```

feat: remove env filter and add support for 97

---

package.json

```bash
```
**Desktop:**
- OS:

build: update package version to 0.2

---

config/config.example.yaml
src/api/accounts/accounts-discord/accounts-discord.controller.ts
src/api/accounts/accounts-discord/accounts-discord.module.ts
src/api/accounts/accounts-discord/accounts-discord.service.ts
src/api/accounts/accounts-discord/dto/accounts-login-discord.dto.ts
src/api/accounts/accounts-discord/dto/accounts-signup-discord.dto.ts
src/api/accounts/types/index.ts
src/app/module.ts

```bash
```
w3itch-crafter/w3itch-frontend#106
**Desktop:**
- OS:

feat: discord integration

---

src/api/accounts/accounts-discord/accounts-discord.controller.ts
src/api/accounts/accounts-discord/accounts-discord.service.ts
src/api/accounts/accounts-discord/dto/accounts-bind-discord.dto.ts
src/api/accounts/accounts-github/accounts-github.controller.ts
src/api/accounts/accounts-github/accounts-github.service.ts
src/api/accounts/accounts-github/dto/accounts-bind-github.dto.ts
src/api/accounts/accounts-metamask/accounts-metamask.controller.ts
src/api/accounts/accounts-metamask/accounts-metamask.service.ts
src/api/accounts/accounts-metamask/dto/accounts-bind-metamask.dto.ts
src/api/accounts/accounts.controller.ts
src/api/accounts/accounts.service.ts
src/api/accounts/types/index.ts

```bash
```
**Desktop:**
- OS:

feat: 3rd party platform binding

---

thirdparty/minetest/index.html

- dierect connect to server
```bash
```
FYI: https://github.com/w3itch-crafter/w3itch-minetest-frontend/blob/mint/public/minetest/index.html#L198
Supports direct connection to the server by passing in URL parameters, no need to select a server and enter username and password …

feat: support address & name

---

.drone.yml
config/config.example.yaml
package.json
src/api/blockchains/tokens/tokens.service.ts
src/api/blockchains/tokens/web3.provider.ts
src/api/games/default.games.service.ts
src/api/games/easy-rpg.games.service.ts
src/api/games/game-projects.controller.ts
src/api/games/games.base.service.ts
src/api/games/games.logic.service.spec.ts
src/api/games/games.logic.service.ts
src/api/games/games.module.ts
src/api/games/minetest.games.controller.ts
src/api/games/minetest.games.service.spec.ts
src/api/games/minetest.games.service.ts
src/api/games/specific.games.service.ts
src/api/games/type/index.d.ts
src/api/minetest/controller.ts
src/entities/MinetestWorld.entity.ts
src/types/enum.ts
src/types/index.d.ts
test/minetest-server/minetest.30001.conf
test/minetest-server/worlds/world1/world.mt
yarn.lock

``` yaml
game:
minetest:
basePath: /home/w3itch/.minetest
binPath: /home/w3itch/minetest.sh
execMinetestEnabled: true
ports:
begin: 30030
```
https://github.com/w3itch-crafter/w3itch-frontend/issues/181
- Upload world.zip file ,then start a server
- More game query criteria
Find …

feat: minetest

---

.drone.yml
config/config.example.yaml
package.json
src/api/games/games.logic.service.spec.ts
src/api/games/games.module.ts
src/api/games/minetest.games.service.spec.ts
src/api/games/minetest.games.service.ts
src/api/storages/module.ts
src/api/storages/service.ts
src/entities/Game.entity.ts
yarn.lock

GameProjectDTO doesn't require cover property
```bash
```
w3itch-crafter/w3itch-frontend#199
**Desktop:**
- OS:

feat: automatic minetest world cover generation

---

src/api/accounts/accounts.service.ts

```bash
```
**Desktop:**
- OS:

fix: could not login

---

src/api/games/games.logic.service.spec.ts
src/types/enum.ts

Remove `default` kind of project submitted to the back-end API.Use `downloadable` instead.
`default` is used on the front-end for auto-detacting kind of the project.
```bash
```
**Desktop:**
- OS:
- OS: [e.g. …

feat!: Support downloadable kind of game project

---

src/api/games/games.base.service.ts
src/api/games/games.logic.service.spec.ts
src/api/games/games.module.ts
src/api/games/minetest-worlds/minetest-worlds.module.ts
src/api/games/minetest-worlds/minetest-worlds.service.ts
src/api/games/minetest.games.controller.ts
src/api/games/minetest.games.service.spec.ts
src/api/games/minetest.games.service.ts
src/configs/ormconfig.ts
src/entities/MinetestWorld.entity.ts
src/migrations/1654155096433-InitMinetestWorldRelation.ts
src/types/enum.ts
test/minetest-server/minetest.30001.conf

```bash
```
There is an additional function that uses the existing configuration.
The `minetest.conf.template` file can be placed in the directory specified by `game.minetest.basePath`
Add minetest world entity to allow the port, minetest.conf configuration file to bind to the world stably and avoid …

feat: add mintest world entity & minetest.conf template

---

src/api/games/games.logic.service.ts
src/entities/Game.entity.ts
src/migrations/1654651539899-AlterGameDescLength.ts
src/types/enum.ts

```bash
```
https://github.com/w3itch-crafter/w3itch-frontend/issues/255
1. Support more classifications
5. Support for sufficiently long descriptions with rich media
https://backend-api.testenv.w3itch.io/api/#/Game%20Projects/GameProjectsController_createGameProject
Request
``` json
{
"title": …
```

feat: Support more classifications & long desc

---

src/api/games/dto/update-game-proejct.dto.ts
src/api/games/games.logic.service.ts

remove 'kind' & 'classification' field in update-game payload https://backend-api.testenv.w3itch.io/api/#/Game%20Projects/GameProjectsController_updateGameProject
- [] No
```bash
```
kind & classification could not be modified 
**Desktop:**
https://backend-api.testenv.w3itch.io/api/#/Game%20Projects/Ga …

fix!: kind is incorrectly updated

---

src/api/accounts/accounts-github/accounts-github.service.ts

```bash
```
**Desktop:**
- OS:

fix: get github username

---

src/api/users/dto/update-user.dto.ts
src/entities/User.entity.ts
src/migrations/1655646827134-AlterTableUserAvatar.ts

```bash
```
Fixes #58 
**Desktop:**
- OS:
- Browser [firefox]

fix: default link of avatar

---

src/api/games/game-projects.controller.ts
src/api/games/games.base.service.ts
src/api/games/games.logic.service.spec.ts
src/api/games/games.logic.service.ts
src/api/users/users.module.ts

Reverts w3itch-crafter/w3itch-backend#67

Revert "feat: remove uncessary queries in getProjectIdByURL and check whete…"
